@hostAddress = https://kadenanodes.futurepenguin.com
@apiAddress  = {{hostAddress}}/kadenanodes/api/v1

### Get nodes

GET {{apiAddress}}/nodes?date=2024-03-08
Accept: application/json

### Get the number of nodes grouped by dates

GET {{apiAddress}}/nodes/count?dateFrom=2024-03-22&dateTo=2024-03-22
Accept: application/json



// nodes/countries

### Get the number of nodes grouped by country - filtered by date

GET {{apiAddress}}/nodes/countries/count?date=2024-03-07
Accept: application/json

### Get the number of nodes grouped by country - filtered by date and status online

GET {{apiAddress}}/nodes/countries/count?date=2024-03-25&isOnline=true
Accept: application/json

### Get the number of nodes grouped by country - filtered by date and status offline

GET {{apiAddress}}/nodes/countries/count?date=2024-01-30&isOnline=false
Accept: application/json

### Get the number of nodes grouped by country - filtered by date and nodeVersion

GET {{apiAddress}}/nodes/countries/count?date=2024-03-07&nodeVersion=2.23
Accept: application/json

### Get the number of nodes grouped by country - filtered by date, status online and nodeVersion

GET {{apiAddress}}/nodes/countries/count?date=2024-03-07&isOnline=true&nodeVersion=2.23
Accept: application/json



// nodes/versions

### Get the number of nodes grouped by version

GET {{apiAddress}}/nodes/versions/count?date=2024-09-07
Accept: application/json

### Get the number of nodes grouped by version - online

GET {{apiAddress}}/nodes/versions/count?date=2024-04-08&isOnline=true
Accept: application/json

### Get the number of nodes grouped by version - offline

GET {{apiAddress}}/nodes/versions/count?date=2024-05-15&isOnline=true
Accept: application/json



// nodes/stats

### Get stats

GET {{apiAddress}}/nodes/stats
Accept: application/json