version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - webapi
    networks:
      - nginx-network

  webapi:
    build: ./webapi
    container_name: kadenanodewatcher-webapi
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ../../data/db
        target: /app/data/db
      - type: bind
        source: ../logs
        target: /app/infra/logs
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
