version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: kadenanodewatcher-nginx
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - webapi
    networks:
      - nginx-network

  webapi:
    build: ./webapi
    container_name: kadenanodewatcher-webapi
    restart: unless-stopped
    ##ports: Commented out because we do not expose it outside the internal network.
    ##  - "8080:8080"
    volumes:
      - type: bind
        source: ../../data/db
        target: /app/data/db
      - type: bind
        source: ../logs
        target: /app/infra/logs
    depends_on:
      - cache
    environment:
      - CONNECTIONSTRINGS__RedisCache=cache:6379,password=redis123##!!
    networks:
      - nginx-network
  
  cache:
    image: redis:latest
    container_name: kadenanodewatcher-redis
    restart: always
    ##ports: Commented out because we do not expose it outside the internal network.
    ##  - '5013:6379'
    command: [ "redis-server", "--requirepass", "redis123##!!" ]
    networks:
      - nginx-network
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
